#!/usr/bin/env bash

exec docker build -t my/asciidoc${ver} \
    ${http_proxy:+--build-arg http_proxy="$http_proxy"} ${https_proxy:+--build-arg https_proxy="$https_proxy"} ${no_proxy:+--build-arg no_proxy="$no_proxy"} \
    .
